---
sudo: false

services:
  - docker

language: go

go:
  - 1.7.4

before_install:
  - docker build -t yelp-review-extractor -f resources/Dockerfile .

script:
  - docker run yelp-review-extractor

notifications:
  on_success: always
  email: false
  slack:
    secure: "A/+wUxVe4ST+MKA3w5uRpFf8YsoWl14BERy4qd9VAmUVzsGcXI569yPUe1/MlLstMVBCAlFW8KQBwxZziegIzTGOG8QlgkLmOfmaiJGf70fKDvHuJw0+pFYfMb6M0jAK7IVC7dgTxDZT2X8s9myNahqfrSHPWUgtv4CIlhw5cKSJl/xgfzoqNXJ9zn03j2kEJHimlB/h4TaqVRRvP514wCbmXwGAv5XzqfOXjdzRnVSyXWHos15Y0/PT/5CSTBAzho9ZMiGv2QOpoYOI5RD8YTMxUjOaDq3/c+OkfUBvfWug/DEdDs4xggRMY96YMM4K7e4CFl6ycm6aIcqW/cVTdolwadOn8uLlS7LXwNM2opebP5e/wOFFZVLvcSFp16vvoFYlfvegv/S3+WRWzGGVWe0h9dpTSdGURAvoCRsk2BbY/PXafzVzHvUSnvOsYupEBj1nw4hViJ7NtvgQM3rhXyoxrWYgQrPSVvlcyU5dOr3F3U2lA7hDGD5U4/Ee6j3rIc9BE3oXozb7pICWSFBOg3wBBY9z63hbbvXnNLgmfJRKpmFN/nuQ9BqHo3o3pw9Y7hufLYHBxV8toeBdgLGW4haWWxMKBeRoWAbzQT2jX0Y6qIwamJkUp6XX9IGcXUSvebjbBWrcW3yIq4QiTNbZhGycLQtmdchOyQ34PIQhdv8="
...
